import type { Metadata } from "next";
import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import "./globals.css";

const bowlby = Bowlby_One_SC({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-bowlby-one-sc",
  weight: ["400"],
});

const dmMono = DM_Mono({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-dm-mono",
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Suburbia Skate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bowlby.variable} ${dmMono.variable} antialiased font-mono`}>
        <main>
          {children}

        </main>
      </body>
    </html>
  );
}
